meta_product_name: "JustInvoice"

meta_title: "JustInvoice – Send your invoices in just a few clicks"

meta_description: "A quick and easy way to create and send your invoices"

meta_image: "logo.png"
